---
title: 'RPEP significance testing 2'
author: "Milena"
date: "7-4-2022"
output: html_document
---

```{r}
# STEP 1: load packages and data
rm(list=ls()) # clear the working directory
library (reshape) # load library
library (ez) # load library
library (Hmisc) # required for %nin%
library (ggplot2)
library(doBy)
library(reshape2)
library(tidyverse)
# load the data
load(file = "C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\dataframe input 2.Rdata") 
load(file = "C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\corr_conditions2.Rdata") 
```


```{r}
# STEP 2: Prepare the data, adjust the choice value & create melted object variables

# melt the data
input2.melt <- melt(input_2, 
                   id.var = c('participant', 'outPrev', 'condition', 'manipulation','gender'), 
                   measure.vars = c('startRT','choiceRT'))
input2.melt$condition <- factor(input2.melt$condition) 
```


\section{Distribution of the start RT and choiceRT}

```{r}
#startRT distribution 
plot <- ggplot(input_2,aes(x=trial_number, y=startRT)) + 
  stat_summary(fun = mean, geom = "point") +
  scale_x_continuous(breaks  = c(18,33,48,63,78,93,108))
## this shows that in the first 15 trials of the experiment the participants are slower to respond
# -> this happens to be a loss sequence -> is it because of the losses they are slower - or because it is the beginning and they are still getting to know the game/ are still thinking a lot about which option to choose - or a combination?
# if there is a lower RT in the loss condition it might be because of this first sequence
# can I do the analysis again without the first block?
ggsave(filename="C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\output_2\\startRT\\startRT distribution.png", 
       plot = plot, 
       device = "png",
       width = 150, 
       height = 150, 
       dpi = 600,
       units = "mm")


#choiceRT distribution
plot <- ggplot(input_2,aes(x=trial_number, y=choiceRT)) + 
  stat_summary(fun = mean, geom = "point")
ggsave(filename="C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\output_2\\choiceRT\\choiceRT distribution.png", 
       plot = plot, 
       device = "png",
       width = 150, 
       height = 150, 
       dpi = 600,
       units = "mm")
```

1) Analysis of the start RT

```{r}
# testing the significance with the predictors condition, manipulation and previous outcome
start.cast <- cast(input2.melt, participant + condition + manipulation + outPrev ~ ., mean, subset = variable == "startRT")
names(start.cast)[5] <- "startRT"

# first: plot it
# plot the interaction between previous outcome and start RT
plot <- ggplot(start.cast,aes(x=outPrev, y=startRT)) + 
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line", aes(group = 1)) + 
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", width = 0.10)
ggsave(filename="C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\output_2\\startRT\\startRT x outPrev.png", 
       plot = plot, 
       device = "png",
       width = 150, 
       height = 150, 
       dpi = 600,
       units = "mm")
# w/ condition
plot <- ggplot(start.cast, aes(y = startRT, x = outPrev, fill = condition)) +
  geom_boxplot()+
  theme_minimal() 
ggsave(filename="C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\output_2\\startRT\\startRT x outPrev x condition.png", 
        plot = plot, 
        device = "png",
        width = 150, 
        height = 150, 
        dpi = 600,
        units = "mm")
# w/ manipulation
plot <- ggplot(start.cast, aes(y = startRT, x = outPrev, fill = manipulation)) +
  geom_boxplot()+
  theme_minimal() 
ggsave(filename="C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\output_2\\startRT\\startRT x outPrev x manipulation.png", 
        plot = plot, 
        device = "png",
        width = 150, 
        height = 150, 
        dpi = 600,
        units = "mm")


output1 <- ezANOVA(
  data = start.cast
  , dv = .(startRT) # the column in data w/ the dependent variable
  , wid = .(participant) # the column w/ the identifier
  , within = .(outPrev, condition) # within-subj. variable
  , between = .(manipulation) # between-subj. variable
  , observed = .(manipulation) # this variable was observed, not manipulated
  , detailed = T
)

output1

# the effect of previous outcome is significant: startRT is faster after a loss 
# F(1,97) = 76.39324792, with p = 7.004648e-14	 which is < 0.05

# the effect of condition is no longer significant!

# the interaction between condition and previous outcome is not significant -> the start reaction time given the previous outcome does not depend on the condition
```
```{r}
output2 <- ezANOVA(
  data = start.cast
  , dv = .(startRT) # the column in data w/ the dependent variable
  , wid = .(participant) # the column w/ the identifier
  , within = .(outPrev, condition) # within-subj. variable
  , detailed = T
)

output2

# same conclusions
# these are the one I report!
# -> conclusions don't change when integrating manipulation
# however: not enough participants
```

```{r}
# another way (but not sure whether this is legit)

# plot it
# plot <- ggplot(corr_conditions, aes(y = diffWL, x = condition, fill = manipulation)) +
#   geom_boxplot()+
#   theme_minimal() 
# ggsave(filename="C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\output\\startRT\\startRT x outPrev x manipulation 2.png", 
#         plot = plot, 
#         device = "png",
#         width = 150, 
#         height = 150, 
#         dpi = 600,
#         units = "mm")
# 
# 
# output <- ezANOVA(
#   data = corr_conditions
#   , dv = .(diffWL) # the column in data w/ the dependent variable
#   , wid = .(participant) # the column w/ the identifier
#   , within = .(condition) # within-subj. variable
#   , between = .(manipulation) # between-subj. variable
#   , observed = .(manipulation) # this variable was observed, not manipulated
#   , detailed = T
# )
# 
# output
# 
# # nothing significant -> the condition is no longer significant 
# # however a trend is visible on the boxplot: the PLS seems to be (a bit) stronger for those that answered "yes" 
```

```{r}
source("pairwise_comparisons.R") 
start.pc <- dcast(start.cast, participant ~ outPrev,  mean, value.var = 'startRT') # long to wide
pc1 <- TES(start.pc$"-5", start.pc$"+5", paired = TRUE)
output <- rbind(pc1)
row.names(output) <- c('Loss vs Win')
output

# not sure whether I've done this correctly
# and not sure what the output means
# confidence interval (for the difference in startRT between loss and win): [-109.804; -69.104]
# gav = Hedges' g = 0.506 ~ a medium effect 
```
2) Analysis of the choice RT}
-> Does the outcome of the previous trial influence choice latencies?}

```{r}
# the same process but with choiceRT
choice.cast <- cast(input2.melt, participant + condition + manipulation + outPrev ~ ., mean, subset = variable == "choiceRT")
names(choice.cast)[5] <- "choiceRT"

# plot the data 
plot<- ggplot(choice.cast,aes(x=outPrev, y=choiceRT)) + 
  stat_summary(fun.y = mean, geom = "point") +
  stat_summary(fun.y = mean, geom = "line", aes(group = 1)) + 
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", width = 0.10)

plot + theme(axis.text.x  = element_text(size=12),
             axis.text.y  = element_text(size=12),
             axis.title.x  = element_text(size=14),
             axis.title.y  = element_text(size=14)) + coord_cartesian(ylim = c(400,800)) + theme_bw()

ggsave(filename="C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\output_2\\choiceRT\\choiceRT x outPrev.png", 
        plot = plot, 
        device = "png",
        width = 150, 
        height = 150, 
        dpi = 600,
        units = "mm")


# show the means and SD
summaryBy(choiceRT ~ outPrev, data=as.data.frame(choice.cast),  FUN=c(mean,sd))

# plot it for condition
plot <- ggplot(choice.cast, aes(y = choiceRT, x = outPrev, fill = condition)) +
  geom_boxplot()+
  theme_minimal() 
ggsave(filename="C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\output_2\\choiceRT\\choiceRT x outPrev x condition.png", 
        plot = plot, 
        device = "png",
        width = 150, 
        height = 150, 
        dpi = 600,
        units = "mm")

# plot it for manipulation
plot <- ggplot(choice.cast, aes(y = choiceRT, x = outPrev, fill = manipulation)) +
  geom_boxplot()+
  theme_minimal() 
ggsave(filename="C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\output_2\\choiceRT\\choiceRT x outPrev x manipulation.png", 
        plot = plot, 
        device = "png",
        width = 150, 
        height = 150, 
        dpi = 600,
        units = "mm")


output1 <- ezANOVA(
  data = choice.cast
  , dv = .(choiceRT) # the column in data w/ the dependent variable
  , wid = .(participant) # the column w/ the identifier
  , within = .(outPrev, condition) # within-subj. variable
  , between = .(manipulation) # between-subj. variable
  , observed = .(manipulation) # this variable was observed, not manipulated
  , detailed = T
)

output1

# significant effect of previous outcome on the choiceRT
# NO significant effect of condition on the choiceRT 
```
```{r}
output2 <- ezANOVA(
  data = choice.cast
  , dv = .(choiceRT) # the column in data w/ the dependent variable
  , wid = .(participant) # the column w/ the identifier
  , within = .(outPrev, condition) # within-subj. variable
  , detailed = T
)

output2

# significant effect of previous outcome on the choiceRT
# NO significant effect of condition on the choiceRT 
```

