---
title: 'RPEP analysis 2'
author: "Milena"
date: "7-4-2022"
output: html_document
---

```{r}
rm(list=ls()) # clear the working directory
library (reshape) # load library
library (ez) # load library
library (Hmisc) # required for %nin%
library (ggplot2)
library(doBy)
library(reshape2)
library(tidyverse)
```

```{r}
# STEP 1: load the data
load(file = "dataframe input 2.Rdata") 
```

```{r}
# STEP 2: melt the behavioral data for visualization purposes
input2.melt <- melt(input_2, 
                   id.var = c('participant','outPrev','gender','manipulation','trial_number','condition'), 
                   measure.vars ='startRT') 


input2.melt$outPrev <- factor(input2.melt$outPrev) # tell R outPrev is a factor

```

```{r}
# STEP 3: create a dataframe with the mean startRT after loss and win fpr each participant
# over the two conditions
corr_overall2 <- cast(input2.melt,  participant + gender + manipulation ~ outPrev, mean, subset = variable == "startRT")
# taking the two conditions into account
corr_conditions2 <- cast(input2.melt,  participant + gender + manipulation + condition ~ outPrev, mean, subset = variable == "startRT")


 
# calculate the difference scores for win vs. loss 
# (always start with the higher mean to avoid negative diff scores)
corr_overall2$diffWL <- corr_overall2$"+5" - corr_overall2$"-5"
corr_conditions2$diffWL <- corr_conditions2$"+5" - corr_conditions2$"-5"

##CE: you can make it a bit easier:

# levels(input$outPrev)[levels(input$outPrev)=="+5"] <- "win"
# levels(input$outPrev)[levels(input$outPrev)=="-5"] <- "loss"
# 
#  input %>%
#   select(participant, outPrev, startRT, condition, gender, manipulation) %>%
#   group_by(participant, outPrev, condition, gender, manipulation) %>% 
#   summarize(startRT = mean(startRT, na.rm = TRUE)) %>%
#   pivot_wider(names_from = outPrev, values_from = startRT) %>%
#   mutate(win = as.numeric(win),
#          loss = as.numeric(loss)) %>%
#   mutate(diff = win - loss)-> startRT
# 
#  ## -end of my suggestion-##

```

```{r}
# STEP 4: calculate the means and sds
## the means
# the mean for each condition
dcast(. ~ condition, 
      data = corr_conditions2, mean, value.var = "diffWL")
# the mean for condition x manipulation
dcast(condition ~ manipulation, 
      data = corr_conditions2, mean, value.var = "diffWL")
# the mean for condition x gender
dcast(condition ~ gender, 
      data = corr_conditions2, mean, value.var = "diffWL")
# the mean for condition x manipulation x gender
dcast(condition ~ manipulation + gender, 
      data = corr_conditions2, mean, value.var = "diffWL")

## the sds
# the sd for each condition
dcast(. ~ condition, 
      data = corr_conditions2, sd, value.var = "diffWL")
# the sd for condition x manipulation
dcast(condition ~ manipulation, 
      data = corr_conditions2, sd, value.var = "diffWL")
# the sd for condition x gender
dcast(condition ~ gender, 
      data = corr_conditions2, sd, value.var = "diffWL")
# the sd for condition x manipulation x gender
dcast(condition ~ manipulation + gender, 
      data = corr_conditions2, sd, value.var = "diffWL")

```

```{r}
# this is to make the correct labels for the boxplots
corr_conditions2$condition <- factor(as.character(corr_conditions2$condition), levels = c("Loss_Seq", "Random_Seq"), labels = c("Loss sequence", "Random sequence"))

```

```{r}
## CE: I would make ggplots with start as Y; win/loss as X and condition as color (see my plots in almost all my studies)
# STEP 5: make boxplots!
plot_conditions <- ggplot(corr_conditions2, aes(y = diffWL, x = condition)) +
  geom_boxplot()+
  geom_hline(yintercept=0, linetype="dashed", color = "red") +
  coord_cartesian(ylim = c(-200, 400)) + 
  #ggtitle("Post-loss speeding effect") + 
  theme_minimal() +
  ylab("Post-lost speeding effect in ms") + 
  xlab("Condition") 

ggsave(filename="C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\output_2\\boxplot conditions.png", 
       plot = plot_conditions, 
       device = "png",
       width = 150, 
       height = 150, 
       dpi = 600,
       units = "mm")

plot_conditions_manipulation <- ggplot(corr_conditions2, aes(y = diffWL, x = condition, fill = manipulation)) +
  geom_boxplot()+
  geom_hline(yintercept=0, linetype="dashed", color = "red") +
  coord_cartesian(ylim = c(-200, 400)) + 
  #ggtitle("Post-loss speeding effect") + 
  theme_minimal() +
  ylab("Post-lost speeding effect in ms") + 
  xlab("Condition") +
  guides(fill=guide_legend(title="Yes/no statement"))

ggsave(filename="C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\output_2\\boxplot conditions x manipulation.png", 
       plot = plot_conditions_manipulation, 
       device = "png",
       width = 150, 
       height = 150, 
       dpi = 600,
       units = "mm")

plot_conditions_gender <- ggplot(corr_conditions2, aes(y = diffWL, x = condition, fill = gender)) +
  geom_boxplot()+
  geom_hline(yintercept=0, linetype="dashed", color = "red") +
  coord_cartesian(ylim = c(-200, 400)) + 
  #ggtitle("plot title here") + 
  theme_minimal() +
  ylab("Post-lost speeding effect in ms") + 
  xlab("Gender") +
  guides(fill=guide_legend(title="Gender"))

ggsave(filename="C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\output_2\\boxplot conditions x gender.png", 
       plot = plot_conditions_gender, 
       device = "png",
       width = 150, 
       height = 150, 
       dpi = 600,
       units = "mm")

```

```{r}
# save the dataframes
save(corr_conditions2, file = "C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\corr_conditions2.Rdata")
save(corr_overall2, file = "C:\\Users\\milen\\Dropbox\\Universiteit\\MASTER\\RPEP\\RPEP data analysis\\corr_overall2.Rdata")
```

